/**
[test]

[[test.results]]
value = "5f"

[[test.results]]
value = "12.5f"

[[test.results]]
value = "0f"

[[test.results]]
value = "0f"

[[test.results]]
value = "10f"

[[test.results]]
value = "-5f"

[[test.results]]
value = "15f"

[[test.results]]
value = "-5f"

[[test.results]]
value = "-15f"

[[test.results]]
value = "17.5f"

[[test.results]]
value = "25f"

*/
math::lerp(0.0, 10.0, 0.5);
math::lerp(10.0, 20.0, 0.25);
math::lerp(-10, 10.0, 0.5);
math::lerp(0.0, 10.0, 0.0);
math::lerp(0.0, 10.0, 1);
math::lerp(0.0, 10.0, -0.5);
math::lerp(0.0, 10, 1.5);
math::lerp(-10.0, 0.0, 0.5);
math::lerp(-20.0, -10.0, 0.5);
math::lerp(10.0, 20.0, 0.75);
math::lerp(0, 50, 0.5f);
