/**
[test]

[[test.results]]
value = "false"

[[test.results]]
value = "false"

[[test.results]]
value = "false"

[[test.results]]
value = "true"

[[test.results]]
value = "true"

[[test.results]]
value = "true"

[[test.results]]
value = "false"

[[test.results]]
value = "true"

*/
[1,2,3] < [1,2,3];
[1,2,3] > [1,2,3];

[1,2,3] < [0,1,2];
[1,2,3] > [0,1,2];


[1,2,3] <= [1,2,3];
[1,2,3] >= [1,2,3];

[1,2,3] <= [0,1,2];
[1,2,3] >= [0,1,2];
