/**
[test]
reason = "Tests the math::FRAC_1_SQRT_2, math::SQRT_2 and math::TAU constants"

[[test.results]]
value = "0.7071067811865476f"

[[test.results]]
value = "1.4142135623730951f"

[[test.results]]
value = "6.283185307179586f"

[[test.results]]
value = "0.7071067811865476f"

[[test.results]]
value = "1.4142135623730951f"

[[test.results]]
value = "6.283185307179586f"

[[test.results]]
value = "true"

[[test.results]]
value = "1.0000000000000002f"
*/

math::FRAC_1_SQRT_2;
math::SQRT_2;
math::TAU;
math::frac_1_sqrt_2;
math::sqrt_2;
math::tau;
math::TAU / 2 = math::PI;
math::SQRT_2 * math::FRAC_1_SQRT_2;
