[package]
name = "surrealdb-cnf"
publish = true
readme = "README.md"
documentation = "https://docs.rs/surrealdb-cnf/"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
common.workspace = true
num-traits.workspace = true
path-clean.workspace = true
tracing.workspace = true

[lints]
workspace = true
