[1,a];
/* ===== result =====
Query
    .exprs: Some
        -TopLevelExpr::Expr
            Expr::Array
                Array
                    .entries: Some
                        -Expr::Integer
                            +1
                        -Expr::Path
                            Path
                                .start: Ident
                                    .text: "a"
                                .parts: None
*/