d"2024-06-15T10:30:00Z";
d"+2024-06-15T10:30:00Z";
d"-2024-06-15T10:30:00Z";
d"2024-06-15";
/* ===== result =====
Query
    .exprs: Some
        -TopLevelExpr::Expr
            Expr::DateTime
                2024-06-15T10:30:00Z
        -TopLevelExpr::Expr
            Expr::DateTime
                2024-06-15T10:30:00Z
        -TopLevelExpr::Expr
            Expr::DateTime
                -2024-06-15T10:30:00Z
        -TopLevelExpr::Expr
            Expr::DateTime
                2024-06-15T00:00:00Z
*/