1dec;
1.0dec;
1.0e10dec;
1e10dec;
1e-10dec;
1_2.3_4e1_2dec
/* ===== result =====
Query
    .exprs: Some
        -TopLevelExpr::Expr
            Expr::Decimal
                1
        -TopLevelExpr::Expr
            Expr::Decimal
                1.0
        -TopLevelExpr::Expr
            Expr::Decimal
                10000000000
        -TopLevelExpr::Expr
            Expr::Decimal
                10000000000
        -TopLevelExpr::Expr
            Expr::Decimal
                0.0000000001
        -TopLevelExpr::Expr
            Expr::Decimal
                12340000000000
*/