東京::Москва::Ĳsselmeer;
/* ===== result =====
Query
    .exprs: Some
        -TopLevelExpr::Expr
            Expr::Path
                Path
                    .start: Ident
                        .text: "東京"
                    .parts: Some
                        -PathSegment::Ident
                            Ident
                                .text: "Москва"
                        -PathSegment::Ident
                            Ident
                                .text: "Ĳsselmeer"
*/