INFO FOR ROOT;
INFO FOR ROOT STRUCTURE;
INFO FOR KV STRUCTURE;
/* ===== result =====
Query
    .exprs: Some
        -TopLevelExpr::Expr
            Expr::Info
                Info
                    .kind: InfoKind::Root
                    .structure: false
        -TopLevelExpr::Expr
            Expr::Info
                Info
                    .kind: InfoKind::Root
                    .structure: true
        -TopLevelExpr::Expr
            Expr::Info
                Info
                    .kind: InfoKind::Root
                    .structure: true
*/