/**
[test]

[[test.results]]
value = "1dec"

[[test.results]]
value = "1dec"

[[test.results]]
value = "-1dec"

[[test.results]]
value = "1dec"

[[test.results]]
value = "1dec"

[[test.results]]
value = "-1dec"

[[test.results]]
value = "1.0dec"

[[test.results]]
value = "1.0dec"

[[test.results]]
value = "-1.0dec"

[[test.results]]
value = "1.0dec"

[[test.results]]
value = "1.0dec"

[[test.results]]
value = "-1.0dec"

[[test.results]]
value = "100dec"

[[test.results]]
value = "100dec"

[[test.results]]
value = "-100dec"

[[test.results]]
value = "100dec"

[[test.results]]
value = "100dec"

[[test.results]]
value = "-100dec"

*/
1dec;
+1dec;
-1dec;
(1dec);
(+1dec);
(-1dec);

1.0dec;
+1.0dec;
-1.0dec;
(1.0dec);
(+1.0dec);
(-1.0dec);

1.0e2dec;
+1.0e2dec;
-1.0e2dec;
(1.0e2dec);
(+1.0e2dec);
(-1.0e2dec);

