[package]
name = "surrealdb-kvs"
publish = true
readme = "README.md"
documentation = "https://docs.rs/surrealdb-kvs/"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
# Use a deterministic incrementing counter for the default
# `Transactable::timestamp` implementation instead of an HLC timestamp.
# Intended for tests only.
test-inc-timestamp = []

[dependencies]
surrealdb-cnf.workspace = true

chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
web-time = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
affinitypool = { workspace = true }
num_cpus = { workspace = true }

[lints]
workspace = true
