extend = [
    { path = "Makefile.local.toml" },
    { path = "Makefile.ci.toml" },
]

[config]
skip_core_tasks = true
time_summary = true
reduce_output = true
default_to_workspace = false

[env]
ALL_FEATURES = { value = "allocator,allocation-tracking,storage-mem,storage-surrealkv,storage-rocksdb,storage-tikv,storage-fdb,scripting,http,jwks,ml,storage-fdb-7_3", condition = { env_not_set = ["ALL_FEATURES"] } }
DEV_FEATURES = { value = "allocator,allocation-tracking,storage-mem,storage-surrealkv,storage-rocksdb,scripting,http,jwks,ml", condition = { env_not_set = ["DEV_FEATURES"] } }
SURREAL_LOG = { value = "full", condition = { env_not_set = ["SURREAL_LOG"] } }
SURREAL_USER = { value = "root", condition = { env_not_set = ["SURREAL_USER"] } }
SURREAL_PASS = { value = "root", condition = { env_not_set = ["SURREAL_PASS"] } }
SURREAL_PATH = { value = "memory", condition = { env_not_set = ["SURREAL_PATH"] } }
SURREAL_NAMESPACE = { value = "test", condition = { env_not_set = ["SURREAL_NAMESPACE"] } }
SURREAL_DATABASE = { value = "test", condition = { env_not_set = ["SURREAL_DATABASE"] } }
SURREAL_NIGHTLY_RUST_TOOLCHAIN = { script = ["cat ${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/rust-toolchain.nightly"], condition = { env_not_set = [
    "SURREAL_NIGHTLY_RUST_TOOLCHAIN",
] } }

[tasks.empty]
disabled = true
private = true

[tasks.init]
private = true

[tasks.end]
private = true
