use std::sync::LazyLock;

pub static FOUNDATIONDB_TRANSACTION_TIMEOUT: LazyLock<i32> =
	lazy_env_parse!("SURREAL_FOUNDATIONDB_TRANSACTION_TIMEOUT", i32, 5000);

pub static FOUNDATIONDB_TRANSACTION_RETRY_LIMIT: LazyLock<i32> =
	lazy_env_parse!("SURREAL_FOUNDATIONDB_TRANSACTION_RETRY_LIMIT", i32, 5);

pub static FOUNDATIONDB_TRANSACTION_MAX_RETRY_DELAY: LazyLock<i32> =
	lazy_env_parse!("SURREAL_FOUNDATIONDB_TRANSACTION_MAX_RETRY_DELAY", i32, 500);
