//! Defines the trait that all models need to implement to interface with the rest of the system.
use crate::utils::error::SurrealError;
use candle_transformers::models::mimi::candle_nn::VarBuilder;
use surrealml_tokenizers::Tokenizer;

/// Trait every preset model enum or struct implements.
///
/// * `type Cfg`- the type of the config for this model.
/// * `fn config(&self)` — returns a ready-to-use instance of that struct.
/// * `fn return_tensor_filenames(&self)` — returns a vector of tensor filenames associated with the model.
/// * `fn return_loaded_model(&self, vb)` — returns the loaded model object.
pub trait ModelSpec {
    type Cfg;
    type LoadedModel;

    /// Yields a ready-to-use instance of that struct.
    fn config(&self) -> Self::Cfg;

    /// Yields all the filenames for the weights to be loaded into the model.
    fn return_tensor_filenames(&self) -> Vec<String>;

    /// Yields a loaded model
    fn return_loaded_model(&self, vb: VarBuilder) -> Result<Self::LoadedModel, SurrealError>;

    /// Runs the model with a tokenizer.
    ///
    /// # Arguments
    /// - `model`: The model to be run
    /// - `input_ids`: The embeddings generated by the tokenizer
    /// - `max_steps`: The maximum steps
    fn run_model(
        &self,
        model: &mut Self::LoadedModel,
        input_ids: &[u32],
        max_steps: usize,
        tokenizer: &Tokenizer,
    ) -> Result<String, SurrealError>;
    // fn run_model_raw(
    //     &self,
    //     model: &mut Self::LoadedModel,
    //     input_ids: &[u32],
    //     max_steps: usize,
    //     tokenizer: &Tokenizer,
    // ) -> Result<String, SurrealError>;
}
