/**
[test]

[[test.results]]
value = """
'
'"""

[[test.results]]
value = "'\r'"

[[test.results]]
value = "'\t'"

[[test.results]]
value = "'\f'"

[[test.results]]
value = "'\b'"

[[test.results]]
value = "'\"'"

[[test.results]]
value = '''"'"'''

[[test.results]]
value = "'\\\\'"

[[test.results]]
value = "'\u0000'"

[[test.results]]
value = "'S'"

[[test.results]]
value = "'S'"

*/
"\n";
"\r";
"\t";
"\f";
"\b";
"\"";
"\'";
"\\";
"\0";
"\u0053";
"\u{53}";
