name: 'Setup SurrealDB'
description: 'Download SurrealDB binary and optionally start the server'

inputs:
  start:
    description: 'Whether to start SurrealDB server'
    required: false
    default: 'false'
  binary-path:
    description: 'Path to SurrealDB binary (defaults to downloaded artifact location)'
    required: false
    default: '${{ github.workspace }}/artifacts/surreal'
  args:
    description: 'Additional arguments for SurrealDB start command'
    required: false
    default: '--allow-all -u root -p root'
  health-url:
    description: 'Health check URL'
    required: false
    default: 'http://localhost:8000/health'
  timeout:
    description: 'Timeout in attempts (each attempt waits 2 seconds)'
    required: false
    default: '30'

runs:
  using: 'composite'
  steps:
    - name: Download artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # (Actions must be pinned by commit hash) v4.3.0
      with:
        name: surreal-amd64
        path: ${{ github.workspace }}/artifacts

    - name: Set file permissions
      shell: bash
      run: chmod +x ${{ inputs.binary-path }}

    - name: Start SurrealDB
      if: ${{ inputs.start == 'true' }}
      shell: bash
      run: ${{ inputs.binary-path }} start ${{ inputs.args }} &

    - name: Wait for startup
      if: ${{ inputs.start == 'true' }}
      shell: bash
      run: |
        # Wait for SurrealDB to be ready
        for i in {1..${{ inputs.timeout }}}; do
          if curl -s ${{ inputs.health-url }} > /dev/null 2>&1; then
            echo "SurrealDB is ready"
            exit 0
          fi
          echo "Waiting for SurrealDB to start... (attempt $i/${{ inputs.timeout }})"
          sleep 2
        done

        # Final check
        if ! curl -s ${{ inputs.health-url }} > /dev/null 2>&1; then
          echo "SurrealDB failed to start"
          exit 1
        fi
