name: 'Setup environment'
description: 'Install Rust toolchain, checkout sources, and setup cache'

inputs:
  toolchain:
    description: 'Rust toolchain version'
    required: false
    default: stable
  components:
    description: 'Additional Rust components to install (space-separated)'
    required: false
    default: ''
  targets:
    description: 'Additional targets to install (space-separated)'
    required: false
    default: ''
  cache-key:
    description: 'Additional cache key suffix'
    required: false
    default: ''
  save-cache:
    description: 'Whether to save cache (typically only on main branch)'
    required: false
    default: 'false'
  workspaces:
    description: 'Workspaces to cache (multi-line string)'
    required: false
    default: ''
  cache-directories:
    description: 'Additional cache directories'
    required: false
    default: ''
  free-disk-space:
    description: 'Whether to free disk space by removing pre-installed software'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Free disk space
      if: inputs.free-disk-space == 'true'
      shell: bash
      run: |
        echo "Disk space before cleanup:"
        df -h /

        echo "Removing unnecessary software..."

        # Large language runtimes and toolchains
        sudo rm -rf /usr/share/swift || true
        sudo rm -rf /usr/lib/jvm || true
        sudo rm -rf /opt/maven || true
        sudo rm -rf /usr/share/gradle* || true
        sudo rm -rf /usr/local/lib/android || true
        sudo rm -rf /opt/ghc || true
        sudo rm -rf /opt/hostedtoolcache/CodeQL || true
        sudo rm -rf /usr/local/share/powershell || true
        sudo rm -rf /usr/local/share/vcpkg || true
        sudo rm -rf /usr/share/miniconda || true
        sudo rm -rf /usr/share/mono || true
        sudo rm -rf /var/lib/snapd || true

        # Browsers and drivers
        sudo rm -rf /usr/local/share/chromium || true
        sudo rm -rf /usr/local/share/gecko_driver || true
        sudo rm -rf /opt/microsoft/msedge || true

        # Docs and manuals
        sudo rm -rf /usr/share/doc || true
        sudo rm -rf /usr/share/man || true

        # Cloud tools
        sudo rm -rf /usr/share/az_* || true

        # Clean Docker
        sudo docker image prune --all --force || true

        # Clean apt cache
        sudo apt-get clean || true

        echo "Disk space after cleanup:"
        df -h /

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # stable
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Setup cache
      uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
      with:
        save-if: ${{ inputs.save-cache }}
        shared-key: ${{ inputs.cache-key }}
        workspaces: ${{ inputs.workspaces }}
        cache-directories: ${{ inputs.cache-directories }}
