name: 'Install tools'
description: 'Install tools'

inputs:
  tools:
    description: 'Tools to install'
    required: false
    default: 'cargo-make'

runs:
  using: 'composite'
  steps:
    - name: Install tools
      uses: taiki-e/install-action@3216b6964cbfe053bb8b9a2ef245bd9300e2061d # (Actions must be pinned by commit hash) v2.62.14
      with:
        tool: ${{ inputs.tools }}
