/**
[test]

[[test.results]]
value = "true"

[[test.results]]
value = "false"

[[test.results]]
value = "false"

[[test.results]]
value = "true"

[[test.results]]
value = "true"

[[test.results]]
value = "true"

[[test.results]]
value = "false"

[[test.results]]
value = "false"

[[test.results]]
value = "true"

[[test.results]]
value = "false"

[[test.results]]
value = "false"

[[test.results]]
value = "true"

[[test.results]]
value = "true"

[[test.results]]
value = "true"

[[test.results]]
value = "false"

[[test.results]]
value = "true"

[[test.results]]
value = "false"

[[test.results]]
value = "true"

[[test.results]]
value = "false"

[[test.results]]
value = "1s"

[[test.results]]
value = "2s"

[[test.results]]
value = "2s"

[[test.results]]
value = "0ns"

[[test.results]]
value = "1s"

[[test.results]]
value = "0ns"

*/

1s == 1s;
1s != 1s;
1s == 2s;
1s != 2s;
1s == 1000ms;

1s < 2s;
1s > 2s;
1s >= 2s;
1s <= 2s;
1s > 1s;
1s < 1s;
1s >= 1s;
1s <= 1s;

1s IS 1s;

!1s;
!0s;

1s CONTAINS 1s;
1s CONTAINSNOT 1s;

1s INSIDE 1s;

1s || 2s;
1s && 2s;
0s || 2s;
0s && 2s;
1s || 0s;
1s && 0s;

