/**
[test]

[[test.results]]
value = "NONE"

[[test.results]]
value = "NONE"

[[test.results]]
value = "NONE"

[[test.results]]
value = "NONE"

[[test.results]]
value = "NONE"

*/
DEFINE PARAM $value VALUE 1;
DEFINE PARAM $comment COMMENT "comment";
DEFINE PARAM $permissions_none PERMISSIONS NONE;
DEFINE PARAM $permissions_full PERMISSIONS FULL;
DEFINE PARAM $permissions_specifics PERMISSIONS WHERE true;
