name: 'Run benchmark'
description: 'Download binaries, prepare environment, run benchmark'

inputs:
  config:
    description: 'Configuration name (e.g., memory, rocksdb, embedded-memory)'
    required: true
  database:
    description: 'Database identifier for crud-bench'
    required: true
  endpoint:
    description: 'Endpoint for crud-bench'
    required: false
    default: ''
  description:
    description: 'Human-readable description'
    required: true
  key_type:
    description: 'Key type (integer, string26, string90, string250)'
    required: true
  needs_server:
    description: 'Whether this config needs a SurrealDB server'
    required: true
  crud_bench_revision:
    description: 'crud-bench git revision'
    required: true
  crud_bench_binary_suffix:
    description: 'Suffix for crud-bench binary artifact (e.g., surrealdb, surrealkv, surrealmx)'
    required: false
    default: 'surrealdb'

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      uses: ./.github/actions/setup-environment
      with:
        save-cache: false

    - name: Download SurrealDB binary
      if: ${{ inputs.needs_server == 'true' }}
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: surreal-binary-${{ inputs.config }}
        path: ${{ github.workspace }}/bin
    
    - name: Make SurrealDB binary executable
      if: ${{ inputs.needs_server == 'true' }}
      shell: bash
      run: |
        chmod +x ${{ github.workspace }}/bin/surreal
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
        echo "SurrealDB binary ready"
    
    - name: Checkout crud-bench repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: surrealdb/crud-bench
        ref: ${{ inputs.crud_bench_revision }}
        path: .github/tools/crud-bench
    
    - name: Download crud-bench binary
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: crud-bench-binary-${{ inputs.crud_bench_binary_suffix }}
        path: .github/tools/crud-bench/target/release/
    
    - name: Make crud-bench binary executable
      shell: bash
      run: |
        chmod +x .github/tools/crud-bench/target/release/crud-bench
        echo "crud-bench binary ready"

    - name: Prepare environment
      shell: bash
      run: |
        if [ "${{ inputs.needs_server }}" = "true" ]; then
          mkdir -p ~/surrealdb-data
        else
          mkdir -p ~/crud-bench-data
          chmod 777 ~/crud-bench-data
        fi
        rm -f result*.json result*.html result*.csv

    - name: Optimize system
      shell: bash
      run: |
        sync
        ulimit -n 65536 || true
        ulimit -u unlimited || true
        ulimit -l unlimited || true

    - name: Print system information
      shell: bash
      run: |
        echo "=== System Information ==="
        echo "Hostname: $(hostname)"
        echo "OS: $(uname -s)"
        echo "Kernel: $(uname -r)"
        echo "Architecture: $(uname -m)"
        echo "CPU Info:"
        if [ -f /proc/cpuinfo ]; then
          grep "model name" /proc/cpuinfo | head -1
          echo "CPU Cores: $(nproc)"
        elif command -v sysctl &> /dev/null; then
          sysctl -n machdep.cpu.brand_string
          echo "CPU Cores: $(sysctl -n hw.ncpu)"
        fi
        echo "Memory:"
        if command -v free &> /dev/null; then
          free -h
        elif command -v vm_stat &> /dev/null; then
          vm_stat | head -5
        fi

    - name: Start SurrealDB server
      if: ${{ inputs.needs_server == 'true' }}
      shell: bash
      run: |
        case "${{ inputs.database }}" in
          surrealdb-memory)
            echo "Starting SurrealDB with in-memory storage..."
            surreal start --log error --user root --pass root memory &
            ;;
          surrealdb-rocksdb)
            echo "Starting SurrealDB with RocksDB storage..."
            surreal start --log error --user root --pass root rocksdb:~/surrealdb-data &
            ;;
        esac
        
        echo $! > /tmp/surrealdb.pid
        echo "SurrealDB started with PID $(cat /tmp/surrealdb.pid)"
        
        # Wait for server to be ready
        echo "Waiting for SurrealDB to start..."
        for i in {1..30}; do
          if curl -s http://localhost:8000/health > /dev/null 2>&1; then
            echo "✓ SurrealDB is ready"
            break
          fi
          if [ $i -eq 30 ]; then
            echo "✗ SurrealDB failed to start"
            exit 1
          fi
          sleep 1
        done

    - name: Run benchmark
      shell: bash
      run: |
        cd .github/tools/crud-bench
        
        RESULT_NAME="${{ inputs.config }}-${{ inputs.key_type }}"
        
        CMD="./target/release/crud-bench -d ${{ inputs.database }}"
        
        if [ -n "${{ inputs.endpoint }}" ]; then
          CMD="$CMD --endpoint ${{ inputs.endpoint }}"
        fi
        
        CMD="$CMD -s 10000 -c 12 -t 48 -r -k ${{ inputs.key_type }} -n $RESULT_NAME"
        
        echo "${{ inputs.description }}" > "display_name_${RESULT_NAME}.txt"
        
        echo "Running: $CMD"
        timeout 10m bash -c "eval $CMD"
      env:
        SURREALDB_USER: root
        SURREALDB_PASS: root

    - name: Collect results
      shell: bash
      run: |
        mkdir -p ${{ github.workspace }}/benchmark-results
        cp .github/tools/crud-bench/result*.json ${{ github.workspace }}/benchmark-results/ || true
        cp .github/tools/crud-bench/display_name_*.txt ${{ github.workspace }}/benchmark-results/ || true
        ls -la ${{ github.workspace }}/benchmark-results

    - name: Upload benchmark results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: benchmark-results-${{ inputs.config }}-${{ inputs.key_type }}
        path: ${{ github.workspace }}/benchmark-results/*
        retention-days: 30

    - name: Cleanup
      if: always()
      shell: bash
      run: |
        # Kill SurrealDB server if running
        if [ -f /tmp/surrealdb.pid ]; then
          echo "Stopping SurrealDB server..."
          PID=$(cat /tmp/surrealdb.pid)
          kill $PID 2>/dev/null || true
          for i in {1..10}; do
            if ! kill -0 $PID 2>/dev/null; then
              break
            fi
            sleep 0.5
          done
          rm -f /tmp/surrealdb.pid
        fi
        
        # Clean up data directories
        for dir in ~/surrealdb-data ~/crud-bench-data; do
          if [ -d "$dir" ]; then
            rm -rf "$dir" 2>/dev/null || {
              echo "Warning: Failed to remove $dir, retrying..."
              sleep 1
              rm -rf "$dir" 2>/dev/null || echo "Warning: Could not clean $dir"
            }
          fi
        done
