name: 'Check workspace'
description: 'Run cargo check on the workspace'

inputs:
  save-cache:
    description: 'Whether to save the cargo cache'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      uses: ./.github/actions/setup-environment
      with:
        save-cache: ${{ inputs.save-cache }}

    - name: Install tools
      uses: ./.github/actions/install-tools

    - name: Check workspace
      shell: bash
      run: cargo make ci-check


