/**
[test]

[[test.results]]
value = "1ns"

[[test.results]]
value = "1µs"

[[test.results]]
value = "1µs"

[[test.results]]
value = "1ms"

[[test.results]]
value = "1s"

[[test.results]]
value = "1m"

[[test.results]]
value = "1h"

[[test.results]]
value = "1d"

[[test.results]]
value = "1y"

[[test.results]]
value = "1w"

[[test.results]]
value = "584942417355y3w5d7h15s999ms999µs999ns"

[[test.results]]
value = "true"

*/
1ns;
1us;
1µs;
1ms;
1s;
1m;
1h;
1d;
1y;
1w;

/// Maximum duration
18446744073709551615s999999999ns;

duration::MAX = 18446744073709551615s999999999ns;