name: Feature request
description: File a feature request
title: "Feature: "
labels: ["feature", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an idea for SurrealDB!
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: What is the usecase in which this feature is relevant?
      placeholder: A clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution
      description: Describe the solution and how it might work.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative methods
      description: Describe alternatives you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: SurrealDB version
      description: Copy and paste the output of `surreal version`
      placeholder: surreal 0.0.0 for macOS on aarch64
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: false
  - type: checkboxes
    id: check
    attributes:
      label: Is there an existing issue for this?
      description: Please search [our issues](https://github.com/surrealdb/surrealdb/issues) to see if this bug already exists.
      options:
      - label: I have searched the existing issues
        required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/surrealdb/surrealdb)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
