test.alpha;
test.degree;
test.diskann;
test.l_build;
/* ===== result =====
Query
    .exprs: Some
        -TopLevelExpr::Expr
            Expr::Idiom
                IdiomExpr
                    .left: Expr::Path
                        Path
                            .start: Ident
                                .text: "test"
                            .parts: None
                    .op: IdiomOperator::Field
                        Ident
                            .text: "alpha"
        -TopLevelExpr::Expr
            Expr::Idiom
                IdiomExpr
                    .left: Expr::Path
                        Path
                            .start: Ident
                                .text: "test"
                            .parts: None
                    .op: IdiomOperator::Field
                        Ident
                            .text: "degree"
        -TopLevelExpr::Expr
            Expr::Idiom
                IdiomExpr
                    .left: Expr::Path
                        Path
                            .start: Ident
                                .text: "test"
                            .parts: None
                    .op: IdiomOperator::Field
                        Ident
                            .text: "diskann"
        -TopLevelExpr::Expr
            Expr::Idiom
                IdiomExpr
                    .left: Expr::Path
                        Path
                            .start: Ident
                                .text: "test"
                            .parts: None
                    .op: IdiomOperator::Field
                        Ident
                            .text: "l_build"
*/