use std::fmt::{self, Display};

use anyhow::Result;
use revision::{
	BorrowedReader, DeserializeRevisioned, Revisioned, SerializeRevisioned, SkipRevisioned,
	WalkRevisioned, revisioned,
};
use serde::{Deserialize, Serialize};
use surrealdb_kvs::impl_kv_value_revisioned;
use surrealdb_kvs::value::KVValue;
use uuid::Uuid;

use crate::error::DatastoreError;

#[derive(Copy, Debug, Clone, PartialEq)]
pub struct MajorVersion(u16);

impl From<u16> for MajorVersion {
	fn from(version: u16) -> Self {
		MajorVersion(version)
	}
}

impl From<Option<u16>> for MajorVersion {
	fn from(v: Option<u16>) -> Self {
		v.unwrap_or(0).into()
	}
}

impl From<MajorVersion> for u16 {
	fn from(v: MajorVersion) -> Self {
		v.0
	}
}

impl KVValue for MajorVersion {
	type KeyContext = ();

	#[inline]
	fn kv_encode_value(&self) -> Result<Vec<u8>> {
		Ok(self.0.to_be_bytes().to_vec())
	}

	#[inline]
	fn kv_decode_value(v: &[u8], _: ()) -> Result<Self> {
		let bin = v.try_into().map_err(|_| DatastoreError::InvalidStorageVersion)?;
		let val = u16::from_be_bytes(bin).into();
		Ok(val)
	}
}

impl MajorVersion {
	/// The latest version
	pub const LATEST: u16 = 3;
	/// The latest version
	pub fn latest() -> Self {
		Self(Self::LATEST)
	}
	/// SurrealDB version 1
	pub fn v1() -> Self {
		Self(1)
	}
	/// SurrealDB version 2
	pub fn v2() -> Self {
		Self(2)
	}
	/// Check if we are running the latest version
	pub fn is_latest(self) -> bool {
		self.0 == Self::LATEST
	}
}

/// The full semantic version of the build that last advanced this datastore,
/// stored cluster-wide at `/!vs`.
///
/// A newtype rather than a bare [`semver::Version`] because `KVValue` and
/// `Version` are both foreign to this crate; the wrapper is also where the
/// comparison rule below lives, which the natural ordering gets wrong.
///
/// Stored as its own string, so what a key dump shows is the version a human
/// would write.
#[derive(Clone, Debug, Eq, PartialEq, Hash, Serialize, Deserialize)]
pub struct StorageVersion(pub semver::Version);

impl_kv_value_revisioned!(StorageVersion);

impl StorageVersion {
	/// The version attributed to a datastore that carries a major version of 3
	/// but no `/!vs` stamp. 3.3.0 is the release that introduced the stamp, so
	/// such a datastore was last written somewhere in `[3.0.0, 3.3.0)`. Taking
	/// the bottom of that window makes every migration introduced in the window
	/// eligible, which is the safe direction: migrations are required to be
	/// idempotent, so running one that was not strictly needed is harmless,
	/// while skipping one is not.
	pub const PRE_STAMP: Self = Self(semver::Version {
		major: 3,
		minor: 0,
		patch: 0,
		pre: semver::Prerelease::EMPTY,
		build: semver::BuildMetadata::EMPTY,
	});

	/// The version of the running build.
	pub fn current() -> Self {
		// `CARGO_PKG_VERSION` is generated by cargo from the manifest and is
		// always valid semver, so a parse failure here is unreachable. Every
		// crate in the workspace carries the same version, so reading this
		// crate's is reading the build's.
		Self::parse(env!("CARGO_PKG_VERSION"))
			.expect("the crate's own version is not valid semver, which cargo cannot produce")
	}

	/// Parses a semantic version string.
	pub fn parse(version: &str) -> Result<Self> {
		Ok(Self(semver::Version::parse(version)?))
	}

	/// The release this version belongs to.
	///
	/// Migration selection and upgrade detection compare on this rather than on
	/// [`semver::Version`]'s own ordering, which sorts a pre-release *below* its
	/// release: under that rule `3.3.0-nightly` would skip the migrations
	/// `3.3.0` runs, so every nightly and CI build would disagree with the
	/// release it precedes.
	pub fn triple(&self) -> (u64, u64, u64) {
		(self.0.major, self.0.minor, self.0.patch)
	}

	/// The version a release triple names.
	pub fn from_triple((major, minor, patch): (u64, u64, u64)) -> Self {
		Self(semver::Version::new(major, minor, patch))
	}
}

impl Display for StorageVersion {
	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
		Display::fmt(&self.0, f)
	}
}

// Stored as the string `semver` itself round-trips through, so the encoding
// cannot disagree with the parser and a stored version needs no separate
// consistency check.
impl Revisioned for StorageVersion {
	fn revision() -> u16 {
		String::revision()
	}
}

impl SerializeRevisioned for StorageVersion {
	fn serialize_revisioned<W: std::io::Write>(&self, w: &mut W) -> Result<(), revision::Error> {
		SerializeRevisioned::serialize_revisioned(&self.0.to_string(), w)
	}
}

impl DeserializeRevisioned for StorageVersion {
	fn deserialize_revisioned<R: std::io::Read>(r: &mut R) -> Result<Self, revision::Error> {
		let raw: String = DeserializeRevisioned::deserialize_revisioned(r)?;
		Self::parse(&raw).map_err(|e| revision::Error::Deserialize(e.to_string()))
	}
}

impl SkipRevisioned for StorageVersion {
	fn skip_revisioned<R: std::io::Read>(r: &mut R) -> Result<(), revision::Error> {
		<String as SkipRevisioned>::skip_revisioned(r)
	}
}

impl WalkRevisioned for StorageVersion {
	// Parameterised on `Self`, not on `String`: the walker's `decode` dispatches
	// through this type's `DeserializeRevisioned`, which is where the version is
	// parsed. A `String` walker would hand a caller the raw text and skip that.
	type Walker<'r, R: BorrowedReader + 'r> = revision::LeafWalker<'r, Self, R>;

	fn walk_revisioned<'r, R: BorrowedReader>(
		reader: &'r mut R,
	) -> Result<Self::Walker<'r, R>, revision::Error> {
		Ok(revision::LeafWalker::new(reader))
	}
}

// The stored shape is a length-prefixed string, so a reader can borrow the
// bytes without decoding them.
impl revision::LengthPrefixedBytes for StorageVersion {}

/// One entry in the datastore's version history, stored at `/!vh{ts}{nd}`.
///
/// An entry is written only when a node advances the datastore's stamped
/// version, so the history is the sequence of versions the datastore has
/// progressed through rather than a log of every startup. Entries are keyed by
/// the writing node so that appends from different nodes never target the same
/// key, which matters on backends that resolve concurrent writes by
/// last-writer-wins rather than by conflict.
#[revisioned(revision = 1)]
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, Hash)]
pub struct VersionHistoryEntry {
	/// The version the datastore was stamped with before this entry. `None` for
	/// the entry that first stamps a datastore, whether because it was newly
	/// created or because it predates the stamp.
	pub from: Option<StorageVersion>,
	/// The version the datastore was stamped with by this entry.
	pub to: StorageVersion,
	/// The node that recorded the entry.
	pub node: Uuid,
	/// The datastore clock reading when the entry was recorded.
	pub timestamp: u64,
}

impl_kv_value_revisioned!(VersionHistoryEntry);

/// The record of one applied data migration, stored cluster-wide at `/!mg{id}`.
///
/// The presence of the key is what marks a migration as applied; the fields are
/// diagnostic. Writing it is a separate transaction from the migration's own
/// work, so a crash in between leaves the migration eligible to run again —
/// which is why migrations are required to be idempotent.
#[revisioned(revision = 1)]
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, Hash)]
pub struct MigrationRecord {
	/// The migration's human-readable name.
	pub name: String,
	/// The release that introduced the migration.
	pub version: StorageVersion,
	/// The node that applied it.
	pub node: Uuid,
	/// The datastore clock reading when it was applied.
	pub timestamp: u64,
}

impl_kv_value_revisioned!(MigrationRecord);

#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn test_version_encode_decode() {
		let version = MajorVersion::v2();
		let encoded = version.kv_encode_value().unwrap();
		assert_eq!(encoded, vec![0, 2]);
		let decoded = MajorVersion::kv_decode_value(&encoded, ()).unwrap();
		assert_eq!(decoded, version);
	}

	#[test]
	fn storage_version_keeps_the_reported_string_but_compares_on_the_triple() {
		let nightly = StorageVersion::parse("3.3.0-nightly").unwrap();
		let release = StorageVersion::parse("3.3.0").unwrap();
		assert_eq!(nightly.triple(), release.triple());
		assert_eq!(nightly.to_string(), "3.3.0-nightly");
		assert_ne!(nightly, release);
	}

	#[test]
	fn the_crates_own_version_parses() {
		let current = StorageVersion::current();
		assert_eq!(current.to_string(), env!("CARGO_PKG_VERSION"));
		assert!(current.triple() > StorageVersion::PRE_STAMP.triple());
	}

	/// The stored form is the version's own string, so every shape `semver`
	/// can produce has to survive the trip through it.
	#[test]
	fn storage_version_round_trips() {
		for text in [
			"3.4.1",
			"3.4.1-beta.2",
			"3.4.1+build7",
			"3.4.1-beta.2+build7",
			"3.3.0-nightly",
			"0.0.0",
			"18446744073709551615.0.0",
			"1.0.0-0.3.7",
			"1.0.0-x.7.z.92+exp.sha.5114f85",
		] {
			let version = StorageVersion::parse(text).unwrap();
			assert_eq!(version.to_string(), text, "{text} did not display as itself");

			let encoded = version.kv_encode_value().unwrap();
			assert_eq!(
				StorageVersion::kv_decode_value(&encoded, ()).unwrap(),
				version,
				"{text} did not survive the value encoding"
			);
		}

		assert_eq!(StorageVersion::parse("3.4.1-beta.2+build7").unwrap().triple(), (3, 4, 1));
		assert_eq!(StorageVersion::PRE_STAMP.to_string(), "3.0.0");
		assert_eq!(StorageVersion::from_triple((3, 3, 0)).to_string(), "3.3.0");
	}

	/// A stored value that is not a version is reported, not silently turned
	/// into one — the decoder is `semver`'s parser, so there is no shape it
	/// accepts that the rest of the code would disagree about.
	#[test]
	fn a_malformed_stored_version_is_rejected() {
		let not_a_version = "not.a.version".to_owned().kv_encode_value().unwrap();
		assert!(StorageVersion::kv_decode_value(&not_a_version, ()).is_err());

		let truncated = "3.3".to_owned().kv_encode_value().unwrap();
		assert!(StorageVersion::kv_decode_value(&truncated, ()).is_err());
	}

	#[test]
	fn version_history_entry_round_trips() {
		let entry = VersionHistoryEntry {
			from: Some(StorageVersion::parse("3.2.4").unwrap()),
			to: StorageVersion::parse("3.3.0").unwrap(),
			node: Uuid::from_bytes([7; 16]),
			timestamp: 1_234_567,
		};
		let encoded = entry.kv_encode_value().unwrap();
		assert_eq!(VersionHistoryEntry::kv_decode_value(&encoded, ()).unwrap(), entry);
	}

	#[test]
	fn migration_record_round_trips() {
		let record = MigrationRecord {
			name: "a migration".to_owned(),
			version: StorageVersion::parse("3.3.0").unwrap(),
			node: Uuid::from_bytes([9; 16]),
			timestamp: 42,
		};
		let encoded = record.kv_encode_value().unwrap();
		assert_eq!(MigrationRecord::kv_decode_value(&encoded, ()).unwrap(), record);
	}
}
