name: 'Publish crate'
description: 'Publish crate to crates.io'

inputs:
  publish:
    description: 'Whether to publish (false for dry-run)'
    required: false
    default: 'false'
  nightly-release:
    description: 'Whether this is a nightly release'
    required: false
    default: 'true'
  cargo-registry-token:
    description: 'Token for publishing to crates.io'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      uses: ./.github/actions/setup-environment

    - name: Install release-plz
      shell: bash
      run: |
        curl -L https://github.com/MarcoIeni/release-plz/releases/download/release-plz-v0.3.30/release-plz-x86_64-unknown-linux-gnu.tar.gz | sudo tar -xz -C /usr/bin
        sudo chmod +x /usr/bin/release-plz

    - name: Configure release-plz
      shell: bash
      run: |
        cat << EOF > /tmp/release-plz.toml
        [workspace]
        changelog_update = false
        git_release_enable = false
        semver_check = false
        git_tag_enable = false
        EOF

    - name: Publish the crate
      shell: bash
      env:
        CARGO_REGISTRY_TOKEN: ${{ inputs.cargo-registry-token }}
      run: |
        set -x

        # Create a temporary branch in case the git ref is not a branch
        git checkout -b crate

        if [[ "${{ inputs.publish }}" == "false" || "${{ inputs.nightly-release }}" == "true" ]]; then
          # Dry run - use cargo publish directly as it works better for testing
          cargo publish --workspace --dry-run
        else
          # Real publish - use release-plz for retry logic
          release-plz release --config /tmp/release-plz.toml
        fi


