/**
[test]

[[test.results]]
value = "1dec"

[[test.results]]
value = "1"

[[test.results]]
value = "1f"

[[test.results]]
value = "1dec"

[[test.results]]
value = "1dec"

[[test.results]]
value = "'1dec'"

[[test.results]]
error = "Expected a object but cannot convert 1dec into a object"

[[test.results]]
error = "Expected a array but cannot convert 1dec into a array"

[[test.results]]
error = "Expected a datetime but cannot convert 1dec into a datetime"

[[test.results]]
error = "Expected a duration but cannot convert 1dec into a duration"

[[test.results]]
error = "Expected a point but cannot convert 1dec into a point"

[[test.results]]
error = "Expected a uuid but cannot convert 1dec into a uuid"

[[test.results]]
error = "Expected a record but cannot convert 1dec into a record"

[[test.results]]
error = "Expected a geometry but cannot convert 1dec into a geometry"

[[test.results]]
error = "Expected a set but cannot convert 1dec into a set"

[[test.results]]
error = "Expected a function but cannot convert 1dec into a function"

[[test.results]]
error = "Expected a range but cannot convert 1dec into a range"

*/
<number> 1dec;
<int> 1dec;
<float> 1dec;
<option<decimal>> 1dec;

<decimal> 1dec;
<string> 1dec;
<object> 1dec;
<array> 1dec;
<datetime> 1dec;
<duration> 1dec;
<point> 1dec;
<uuid> 1dec;
<record> 1dec;
<geometry> 1dec;
<set> 1dec;
<function> 1dec;
<range> 1dec;
