/**
[test]

[[test.results]]
value = "1dec"

[[test.results]]
value = "1"

[[test.results]]
value = "1f"

[[test.results]]
value = "1dec"

[[test.results]]
value = "1dec"

[[test.results]]
value = "'1dec'"

[[test.results]]
error = "Expected `object` but found a `1dec`"

[[test.results]]
error = "Expected `array` but found a `1dec`"

[[test.results]]
error = "Expected `datetime` but found a `1dec`"

[[test.results]]
error = "Expected `duration` but found a `1dec`"

[[test.results]]
error = "Expected `geometry` but found a `1dec`"

[[test.results]]
error = "Expected `uuid` but found a `1dec`"

[[test.results]]
error = "Expected `record` but found a `1dec`"

[[test.results]]
error = "Expected `geometry` but found a `1dec`"

[[test.results]]
error = "Expected `array` but found a `1dec`"

[[test.results]]
error = "Expected `function` but found a `1dec`"

[[test.results]]
error = "Expected `range` but found a `1dec`"

*/
<number> 1dec;
<int> 1dec;
<float> 1dec;
<option<decimal>> 1dec;

<decimal> 1dec;
<string> 1dec;
<object> 1dec;
<array> 1dec;
<datetime> 1dec;
<duration> 1dec;
<point> 1dec;
<uuid> 1dec;
<record> 1dec;
<geometry> 1dec;
<set> 1dec;
<function> 1dec;
<range> 1dec;
