/**
[test]

[[test.results]]
value = "1dec"

[[test.results]]
value = "1"

[[test.results]]
value = "1f"

[[test.results]]
value = "1dec"

[[test.results]]
value = "1dec"

[[test.results]]
value = "'1'"

[[test.results]]
value = "'NONE'"

[[test.results]]
value = "'NULL'"

[[test.results]]
error = "Could not cast into `object` using input `1dec`"

[[test.results]]
error = "Could not cast into `array` using input `1dec`"

[[test.results]]
error = "Could not cast into `datetime` using input `1dec`"

[[test.results]]
error = "Could not cast into `duration` using input `1dec`"

[[test.results]]
error = "Could not cast into `geometry` using input `1dec`"

[[test.results]]
error = "Could not cast into `uuid` using input `1dec`"

[[test.results]]
error = "Could not cast into `record` using input `1dec`"

[[test.results]]
error = "Could not cast into `geometry` using input `1dec`"

[[test.results]]
error = "Could not cast into `array` using input `1dec`"

[[test.results]]
error = "Could not cast into `function` using input `1dec`"

[[test.results]]
error = "Could not cast into `range` using input `1dec`"

*/
<number> 1dec;
<int> 1dec;
<float> 1dec;
<option<decimal>> 1dec;
<decimal> 1dec;
<string> 1dec;
<string> none;
<string> null;

<object> 1dec;
<array> 1dec;
<datetime> 1dec;
<duration> 1dec;
<point> 1dec;
<uuid> 1dec;
<record> 1dec;
<geometry> 1dec;
<set> 1dec;
<function> 1dec;
<range> 1dec;
