/**
[test]

[[test.results]]
value = "2129482046"

[[test.results]]
value = "0"

[[test.results]]
value = "3392050242" # a.k.a 0xca2e9442

[[test.results]]
value = "1369346549" # a.k.a 0x519e91f5

[[test.results]]
value = "2181104624"

*/
crypto::joaat('tobie');
crypto::joaat('');

// https://en.wikipedia.org/wiki/Jenkins_hash_function
crypto::joaat('a');
crypto::joaat('The quick brown fox jumps over the lazy dog');

// case-sensitive
crypto::joaat('A');
