/// A surrealql keyword.
#[repr(u8)]
#[derive(Clone, Copy, Eq, PartialEq, Hash, Debug)]
pub enum Keyword {
	After,
	All,
	Analyze,
	As,
	Ascii,
	Assert,
	Before,
	Begin,
	Blank,
	Bm25,
	Break,
	By,
	Camel,
	Cancel,
	ChangeFeed,
	Changes,
	Class,
	Comment,
	Commit,
	Content,
	Continue,
	Cosine,
	Create,
	Database,
	Default,
	Define,
	Delete,
	Diff,
	Dimension,
	Dist,
	Drop,
	Edgengram,
	Euclidean,
	Event,
	Explain,
	False,
	Fetch,
	Field,
	Fields,
	Filters,
	Flexible,
	Fn,
	For,
	From,
	Full,
	Function,
	Group,
	Hamming,
	Ignore,
	Index,
	Info,
	Insert,
	Into,
	If,
	Is,
	Kill,
	Let,
	Limit,
	Live,
	Lowercase,
	Mahalanobis,
	Manhattan,
	Merge,
	Minkowski,
	Model,
	MTree,
	Namespace,
	Ngram,
	NoIndex,
	None,
	Null,
	Omit,
	On,
	Only,
	Option,
	Order,
	Parallel,
	Param,
	Passhash,
	Password,
	Patch,
	Permissions,
	Punct,
	Relate,
	Remove,
	Replace,
	Return,
	Roles,
	Root,
	Schemafull,
	Schemaless,
	Scope,
	Search,
	Select,
	Session,
	Set,
	Show,
	Signim,
	Signup,
	Since,
	Sleep,
	Snowball,
	Split,
	Start,
	Table,
	Then,
	Throw,
	Timeout,
	Tokeizers,
	Token,
	Transaction,
	True,
	Type,
	Unique,
	Unset,
	Update,
	Uppercase,
	Use,
	User,
	Value,
	Version,
	Vs,
	When,
	Where,
	With,
	AllInside,
	AndKw,
	AnyInside,
	Inside,
	Intersects,
	NoneInside,
	NotInside,
	OrKw,
	Outside,
	Not,
	And,
	ContainsAll,
	ContainsAny,
	ContainsNone,
	ContainsNot,
	Contains,
	In,

	Any,
	Array,
	Record,
	Future,
	Bool,
	Bytes,
	Datetime,
	Decimal,
	Duration,
	Float,
	Int,
	Number,
	Object,
	String,
	Uuid,
	Ulid,
	Rand,
	Geometry,
}

impl Keyword {
	pub fn as_str(&self) -> &'static str {
		match *self {
			Keyword::After => "AFTER",
			Keyword::All => "ALL",
			Keyword::Analyze => "ANALYZE",
			Keyword::As => "AS",
			Keyword::Ascii => "ASCII",
			Keyword::Assert => "ASSERT",
			Keyword::Before => "BEFORE",
			Keyword::Begin => "BEGIN",
			Keyword::Blank => "BLANK",
			Keyword::Bm25 => "BM25",
			Keyword::Break => "BREAK",
			Keyword::By => "BY",
			Keyword::Camel => "CAMEL",
			Keyword::Cancel => "CANCEL",
			Keyword::ChangeFeed => "CHANGEFEED",
			Keyword::Changes => "CHANGES",
			Keyword::Class => "CLASS",
			Keyword::Comment => "COMMENT",
			Keyword::Commit => "COMMIT",
			Keyword::Content => "CONTENT",
			Keyword::Continue => "CONTINUE",
			Keyword::Cosine => "COSINE",
			Keyword::Create => "CREATE",
			Keyword::Database => "DATABASE",
			Keyword::Default => "DEFAULT",
			Keyword::Define => "DEFINE",
			Keyword::Delete => "DELETE",
			Keyword::Diff => "DIFF",
			Keyword::Dimension => "DIMENSION",
			Keyword::Dist => "DIST",
			Keyword::Drop => "DROP",
			Keyword::Edgengram => "EDGENGRAM",
			Keyword::Euclidean => "EUCLIDEAN",
			Keyword::Event => "EVENT",
			Keyword::Explain => "EXPLAIN",
			Keyword::False => "false",
			Keyword::Fetch => "FETCH",
			Keyword::Field => "FIELD",
			Keyword::Fields => "FIELDS",
			Keyword::Filters => "FILTERS",
			Keyword::Flexible => "FLEXIBLE",
			Keyword::For => "FOR",
			Keyword::From => "FROM",
			Keyword::Full => "FULL",
			Keyword::Function => "FUNCTION",
			Keyword::Group => "GROUP",
			Keyword::Hamming => "HAMMING",
			Keyword::Ignore => "IGNORE",
			Keyword::Index => "INDEX",
			Keyword::Info => "INFO",
			Keyword::Insert => "INSERT",
			Keyword::Into => "INTO",
			Keyword::If => "IF",
			Keyword::Is => "IS",
			Keyword::Kill => "KILL",
			Keyword::Let => "LET",
			Keyword::Limit => "LIMIT",
			Keyword::Live => "LIVE",
			Keyword::Lowercase => "LOWERCASE",
			Keyword::Mahalanobis => "MAHALANOBIS",
			Keyword::Manhattan => "MANHATTAN",
			Keyword::Merge => "MERGE",
			Keyword::Minkowski => "MINKOWSKI",
			Keyword::Model => "MODEL",
			Keyword::MTree => "MTREE",
			Keyword::Namespace => "NAMESPACE",
			Keyword::Ngram => "NGRAM",
			Keyword::NoIndex => "NOINDEX",
			Keyword::None => "NONE",
			Keyword::Null => "NULL",
			Keyword::Omit => "OMIT",
			Keyword::On => "ON",
			Keyword::Only => "ONLY",
			Keyword::Option => "OPTION",
			Keyword::Order => "ORDER",
			Keyword::Parallel => "PARALLEL",
			Keyword::Param => "PARAM",
			Keyword::Passhash => "PASSHASH",
			Keyword::Password => "PASSWORD",
			Keyword::Patch => "PATCH",
			Keyword::Permissions => "PERMISSIONS",
			Keyword::Punct => "PUNCT",
			Keyword::Relate => "RELATE",
			Keyword::Remove => "REMOVE",
			Keyword::Replace => "REPLACE",
			Keyword::Return => "RETURN",
			Keyword::Roles => "ROLES",
			Keyword::Root => "ROOT",
			Keyword::Schemafull => "SCHEMAFULL",
			Keyword::Schemaless => "SCHEMALESS",
			Keyword::Scope => "SCOPE",
			Keyword::Search => "SEARCH",
			Keyword::Select => "SELECT",
			Keyword::Session => "SESSION",
			Keyword::Set => "SET",
			Keyword::Show => "SHOW",
			Keyword::Signim => "SIGNIM",
			Keyword::Signup => "SIGNUP",
			Keyword::Since => "SINCE",
			Keyword::Sleep => "SLEEP",
			Keyword::Snowball => "SNOWBALL",
			Keyword::Split => "SPLIT",
			Keyword::Start => "START",
			Keyword::Table => "TABLE",
			Keyword::Then => "THEN",
			Keyword::Throw => "THROW",
			Keyword::Timeout => "TIMEOUT",
			Keyword::Tokeizers => "TOKEIZERS",
			Keyword::Token => "TOKEN",
			Keyword::Transaction => "TRANSACTION",
			Keyword::True => "true",
			Keyword::Type => "TYPE",
			Keyword::Unique => "UNIQUE",
			Keyword::Unset => "UNSET",
			Keyword::Update => "UPDATE",
			Keyword::Uppercase => "UPPERCASE",
			Keyword::Use => "USE",
			Keyword::User => "USER",
			Keyword::Value => "VALUE",
			Keyword::Version => "VERSION",
			Keyword::Vs => "VS",
			Keyword::When => "WHEN",
			Keyword::Where => "WHERE",
			Keyword::With => "WITH",
			Keyword::AllInside => "ALLINSIDE",
			Keyword::AndKw => "ANDKW",
			Keyword::AnyInside => "ANYINSIDE",
			Keyword::Inside => "INSIDE",
			Keyword::Intersects => "INTERSECTS",
			Keyword::NoneInside => "NONEINSIDE",
			Keyword::NotInside => "NOTINSIDE",
			Keyword::OrKw => "ORKW",
			Keyword::Outside => "OUTSIDE",
			Keyword::Not => "NOT",
			Keyword::And => "AND",
			Keyword::ContainsAll => "CONTAINSALL",
			Keyword::ContainsAny => "CONTAINSANY",
			Keyword::ContainsNone => "CONTAINSNONE",
			Keyword::ContainsNot => "CONTAINSNOT",
			Keyword::Contains => "CONTAINS",
			Keyword::In => "IN",

			Keyword::Any => "ANY",
			Keyword::Array => "ARRAY",
			Keyword::Geometry => "GEOMETRY",
			Keyword::Record => "RECORD",
			Keyword::Future => "FUTURE",
			Keyword::Bool => "BOOL",
			Keyword::Bytes => "BYTES",
			Keyword::Datetime => "DATETIME",
			Keyword::Decimal => "DECIMAL",
			Keyword::Duration => "DURATION",
			Keyword::Float => "FLOAT",
			Keyword::Fn => "fn",
			Keyword::Int => "INT",
			Keyword::Number => "NUMBER",
			Keyword::Object => "OBJECT",
			Keyword::String => "STRING",
			Keyword::Uuid => "UUID",
			Keyword::Ulid => "ULID",
			Keyword::Rand => "RAND",
		}
	}
}
