[package]
name = "surrealdb-expr"
publish = true
readme = "README.md"
documentation = "https://docs.rs/surrealdb-expr/"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
ml = []
gql = []
scripting = ["dep:js"]
surrealism = []
arbitrary = [
    "dep:arbitrary",
    "surrealdb-sql/arbitrary",
    "surrealdb-types/arbitrary",
    "surrealdb-strand/arbitrary",
    "common/arbitrary",
]

[dependencies]
anyhow.workspace = true
bytes.workspace = true
dmp.workspace = true
arbitrary = { workspace = true, features = ["derive"], optional = true }
chrono = { workspace = true, features = ["serde"] }
common = { workspace = true }
fastnum.workspace = true
geo = { workspace = true, features = ["use-serde"] }
geo-types = { workspace = true }
half.workspace = true
hex.workspace = true
js = { workspace = true, features = [
    "array-buffer",
    "bindgen",
    "classes",
    "futures",
    "loader",
    "macro",
    "parallel",
    "properties",
    "rust-alloc",
], optional = true }
lexicmp.workspace = true
http.workspace = true
quick_cache.workspace = true
rand.workspace = true
reblessive = { workspace = true, features = ["tree"] }
regex.workspace = true
revision = { workspace = true }
rust_decimal = { workspace = true, features = ["maths", "serde-str"] }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json.workspace = true
storekey.workspace = true
surrealdb-cnf = { workspace = true }
surrealdb-collections = { workspace = true }
surrealdb-iam = { workspace = true }
surrealdb-kvs = { workspace = true }
surrealdb-sql = { workspace = true }
surrealdb-strand = { workspace = true }
surrealdb-syn = { workspace = true }
surrealdb-types = { workspace = true }
thiserror.workspace = true
tracing.workspace = true
ulid = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["serde", "v4", "v7"] }

[dev-dependencies]
ahash.workspace = true
rstest.workspace = true
serial_test.workspace = true
tokio = { workspace = true, features = ["macros", "sync", "rt-multi-thread"] }

[target.'cfg(target_family = "wasm")'.dependencies]
jsonwebtoken = { workspace = true, features = ["rust_crypto"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
jsonwebtoken = { workspace = true, features = ["aws_lc_rs"] }

[lints]
workspace = true
