[package]
name = "surrealdb-common"
edition.workspace = true
version.workspace = true
authors.workspace = true
publish = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license-file.workspace = true

[dependencies]
hashbrown.workspace = true
futures.workspace = true
parking_lot.workspace = true
sysinfo.workspace = true


[dev-dependencies]
hashbrown.workspace = true
tokio = { workspace = true, features = ["rt","time"] }

[lints]
workspace = true
