# Start from a base image, e.g., Ubuntu
FROM ubuntu:latest

RUN apt-get update && apt-get install -y curl build-essential
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY . .

# RUN cargo build --release

# CMD ["cargo", "test"]
# run in infinite loop
CMD ["tail", "-f", "/dev/null"]
