/**
[test]

[[test.results]]
value = "1f"

[[test.results]]
value = "1f"

[[test.results]]
value = "-1f"

[[test.results]]
value = "1f"

[[test.results]]
value = "1f"

[[test.results]]
value = "-1f"

[[test.results]]
value = "1f"

[[test.results]]
value = "1f"

[[test.results]]
value = "-1f"

[[test.results]]
value = "1f"

[[test.results]]
value = "1f"

[[test.results]]
value = "-1f"

[[test.results]]
value = "100f"

[[test.results]]
value = "100f"

[[test.results]]
value = "-100f"

[[test.results]]
value = "100f"

[[test.results]]
value = "100f"

[[test.results]]
value = "-100f"

*/
1f;
+1f;
-1f;
(1f);
(+1f);
(-1f);

1.0f;
+1.0f;
-1.0f;
(1.0f);
(+1.0f);
(-1.0f);

1.0e2f;
+1.0e2f;
-1.0e2f;
(1.0e2f);
(+1.0e2f);
(-1.0e2f);

