name: 'Docker build and push'
description: 'Build and optionally push Docker images'

inputs:
  environment:
    description: 'Release environment (nightly, beta, stable)'
    required: true
  tag-prefix:
    description: 'Docker image tag prefix'
    required: true
  build-target:
    description: 'Docker build target (prod-ci or dev-ci)'
    required: true
  tag-suffix:
    description: 'Docker image tag suffix (e.g., -dev)'
    required: false
    default: ''
  push:
    description: 'Whether to push the images'
    required: false
    default: 'false'
  latest:
    description: 'Whether to update the latest tag'
    required: false
    default: 'false'
  docker-user:
    description: 'DockerHub username'
    required: false
  docker-pass:
    description: 'DockerHub password'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set up Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

    - name: Download artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        path: artifacts

    - name: Build Docker image (amd64)
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
      id: build-amd64
      with:
        context: artifacts
        load: true
        platforms: linux/amd64
        file: docker/Dockerfile
        target: ${{ inputs.build-target }}
        tags: surrealdb-local:amd64
        build-args: |
          ARTIFACT_PREFIX=surreal-${{ inputs.tag-prefix }}

    - name: Build Docker image (arm64)
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
      id: build-arm64
      with:
        context: artifacts
        load: true
        platforms: linux/arm64
        file: docker/Dockerfile
        target: ${{ inputs.build-target }}
        tags: surrealdb-local:arm64
        build-args: |
          ARTIFACT_PREFIX=surreal-${{ inputs.tag-prefix }}

    - name: Test the Docker image
      shell: bash
      run: docker run --platform linux/amd64 --rm surrealdb-local:amd64 version

    - name: Configure DockerHub
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
      if: ${{ inputs.push == 'true' }}
      with:
        username: ${{ inputs.docker-user }}
        password: ${{ inputs.docker-pass }}

    - name: Get tag info
      id: tags
      shell: bash
      run: |
        set -x

        tag=surrealdb/surrealdb:${{ inputs.tag-prefix }}${{ inputs.tag-suffix }}
        echo "tag=${tag}" >> $GITHUB_OUTPUT

        if [[ "${{ inputs.environment }}" == "stable" ]]; then
          major=$(echo ${{ inputs.tag-prefix }} | tr "." "\n" | sed -n 1p)
          minor=$(echo ${{ inputs.tag-prefix }} | tr "." "\n" | sed -n 2p)
          echo "tags=${tag},surrealdb/surrealdb:${major}.${minor}${{ inputs.tag-suffix }},surrealdb/surrealdb:${major}${{ inputs.tag-suffix }}"  >> $GITHUB_OUTPUT
        else
          echo "tags=${tag}"  >> $GITHUB_OUTPUT
        fi

    - name: Push to DockerHub
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
      if: ${{ inputs.push == 'true' }}
      with:
        context: artifacts
        push: true
        platforms: linux/amd64,linux/arm64
        file: docker/Dockerfile
        target: ${{ inputs.build-target }}
        tags: ${{ steps.tags.outputs.tags }}
        build-args: |
          ARTIFACT_PREFIX=surreal-${{ inputs.tag-prefix }}

    - name: Pull docker image
      id: image-pull
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: |
        docker pull '${{ steps.tags.outputs.tag }}'

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # 0.29.0
      if: ${{ inputs.push == 'true' }}
      with:
        image-ref: '${{ steps.tags.outputs.tag }}'
        format: 'table'
        exit-code: '1'
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Push to DockerHub (latest)
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
      if: ${{ inputs.push == 'true' && inputs.latest == 'true' }}
      with:
        context: artifacts
        push: true
        platforms: linux/amd64,linux/arm64
        file: docker/Dockerfile
        target: ${{ inputs.build-target }}
        tags: surrealdb/surrealdb:latest${{ inputs.tag-suffix }}
        build-args: |
          ARTIFACT_PREFIX=surreal-${{ inputs.tag-prefix }}


