[package]
name = "rocket-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
surrealdb = { path = "../..", features = ["kv-mem"]}
serde_json = "1.0.127"
thiserror = "1.0.63"
