[package]
name = "surrealdb-engine-api"
publish = true
documentation = "https://docs.rs/surrealdb-engine-api/"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
async-channel.workspace = true
surrealdb-rpc.workspace = true
surrealdb-types.workspace = true
uuid = { workspace = true, features = ["serde", "v4", "v7"] }

[dev-dependencies]
futures = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
