[package]
name = "surrealdb-kvs-indxdb"
publish = true
readme = "README.md"
documentation = "https://docs.rs/surrealdb-kvs-indxdb/"
version.workspace = true
authors.workspace = true
edition.workspace = true
license-file.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
surrealdb-kvs = { workspace = true }
js-sys = { workspace = true }
tracing = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
wasm-bindgen-test = { workspace = true }

[lints]
workspace = true
