name: 'Docker prepare'
description: 'Prepare Docker build matrix and sanitize tag names'

inputs:
  tag-prefix:
    description: 'The prefix of the Docker image tag'
    required: true

outputs:
  tag-prefix:
    description: 'Sanitized tag prefix'
    value: ${{ steps.tag-prefix.outputs.tag-prefix }}
  matrix:
    description: 'Build matrix JSON'
    value: ${{ steps.set-matrix.outputs.matrix }}

runs:
  using: 'composite'
  steps:
    - name: Sanitize tag name
      id: tag-prefix
      shell: bash
      run: |
        echo "tag-prefix=$(echo '${{ inputs.tag-prefix }}' | sed 's/[^a-zA-Z0-9_.-]/-/g' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    # Define matrix here so we don't need to search for it when making changes
    - name: Set matrix
      id: set-matrix
      shell: bash
      env:
        MATRIX: |
          include:
            # Prod image
            - &base_image
              name: Prod image
              build-target: prod-ci
            # Dev image
            - <<: *base_image
              name: Dev image
              build-target: dev-ci
              tag-suffix: -dev

      run: |
        echo '${{ env.MATRIX }}' > matrix.yaml
        echo "matrix=$(yq -o json -I=0 matrix.yaml)" >> $GITHUB_OUTPUT


