/**
[test]

[[test.results]]
value = '""'

[[test.results]]
value = '"Word"'

[[test.results]]
value = '"Word"'

[[test.results]]
value = '"A Sentence With Multiple Words"'

[[test.results]]
value = '"A Sentence With Multiple Words"'

*/
string::capitalize("");
string::capitalize("word");
string::capitalize("Word");
string::capitalize("a sentence with multiple words");
string::capitalize("a Sentence with Multiple words");
