// Code generated by https://github.com/abcum/tmpl
// Source file: kill.gen.go.tmpl
// DO NOT EDIT!

// Copyright © 2016 SurrealDB Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sql

import (
	"time"
)

func (s *SelectStatement) Duration() time.Duration {
	return s.Timeout
}

func (s *CreateStatement) Duration() time.Duration {
	return s.Timeout
}

func (s *UpdateStatement) Duration() time.Duration {
	return s.Timeout
}

func (s *DeleteStatement) Duration() time.Duration {
	return s.Timeout
}

func (s *RelateStatement) Duration() time.Duration {
	return s.Timeout
}

func (s *InsertStatement) Duration() time.Duration {
	return s.Timeout
}

func (s *UpsertStatement) Duration() time.Duration {
	return s.Timeout
}
