// Code generated by https://github.com/abcum/tmpl
// Source file: auth.gen.go.tmpl
// DO NOT EDIT!

// Copyright © 2016 Abcum Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sql

import (
	"testing"

	. "github.com/smartystreets/goconvey/convey"
)

func TestRdwr(t *testing.T) {

	Convey("InfoStatement should auth correctly", t, func() {
		s := &InfoStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("IfStatement should auth correctly", t, func() {
		s := &IfStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("LetStatement should auth correctly", t, func() {
		s := &LetStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("ReturnStatement should auth correctly", t, func() {
		s := &ReturnStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("LiveStatement should auth correctly", t, func() {
		s := &LiveStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("KillStatement should auth correctly", t, func() {
		s := &KillStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("SelectStatement should auth correctly", t, func() {
		s := &SelectStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("CreateStatement should auth correctly", t, func() {
		s := &CreateStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("UpdateStatement should auth correctly", t, func() {
		s := &UpdateStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("DeleteStatement should auth correctly", t, func() {
		s := &DeleteStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("RelateStatement should auth correctly", t, func() {
		s := &RelateStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("InsertStatement should auth correctly", t, func() {
		s := &InsertStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("UpsertStatement should auth correctly", t, func() {
		s := &UpsertStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("DefineNamespaceStatement should auth correctly", t, func() {
		s := &DefineNamespaceStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("RemoveNamespaceStatement should auth correctly", t, func() {
		s := &RemoveNamespaceStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("DefineDatabaseStatement should auth correctly", t, func() {
		s := &DefineDatabaseStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("RemoveDatabaseStatement should auth correctly", t, func() {
		s := &RemoveDatabaseStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("DefineLoginStatement should auth correctly", t, func() {
		s := &DefineLoginStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("RemoveLoginStatement should auth correctly", t, func() {
		s := &RemoveLoginStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("DefineTokenStatement should auth correctly", t, func() {
		s := &DefineTokenStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("RemoveTokenStatement should auth correctly", t, func() {
		s := &RemoveTokenStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("DefineScopeStatement should auth correctly", t, func() {
		s := &DefineScopeStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("RemoveScopeStatement should auth correctly", t, func() {
		s := &RemoveScopeStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("DefineTableStatement should auth correctly", t, func() {
		s := &DefineTableStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("RemoveTableStatement should auth correctly", t, func() {
		s := &RemoveTableStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("DefineEventStatement should auth correctly", t, func() {
		s := &DefineEventStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("RemoveEventStatement should auth correctly", t, func() {
		s := &RemoveEventStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("DefineFieldStatement should auth correctly", t, func() {
		s := &DefineFieldStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("RemoveFieldStatement should auth correctly", t, func() {
		s := &RemoveFieldStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("DefineIndexStatement should auth correctly", t, func() {
		s := &DefineIndexStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

	Convey("RemoveIndexStatement should auth correctly", t, func() {
		s := &RemoveIndexStatement{RW: true}
		w := s.Writeable()
		So(w, ShouldEqual, true)
	})

}
