// Code generated by https://github.com/abcum/tmpl
// Source file: rdwr.gen.go.tmpl
// DO NOT EDIT!

// Copyright © 2016 Abcum Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sql

func (s *InfoStatement) Writeable() bool {
	return false
}

func (s *LetStatement) Writeable() bool {
	return s.RW
}

func (s *LiveStatement) Writeable() bool {
	return true
}

func (s *KillStatement) Writeable() bool {
	return true
}

func (s *ReturnStatement) Writeable() bool {
	return s.RW
}

func (s *IfelseStatement) Writeable() bool {
	return s.RW
}

func (s *SelectStatement) Writeable() bool {
	return s.RW
}

func (s *CreateStatement) Writeable() bool {
	return true
}

func (s *UpdateStatement) Writeable() bool {
	return true
}

func (s *DeleteStatement) Writeable() bool {
	return true
}

func (s *RelateStatement) Writeable() bool {
	return true
}

func (s *InsertStatement) Writeable() bool {
	return true
}

func (s *UpsertStatement) Writeable() bool {
	return true
}

func (s *DefineNamespaceStatement) Writeable() bool {
	return true
}

func (s *RemoveNamespaceStatement) Writeable() bool {
	return true
}

func (s *DefineDatabaseStatement) Writeable() bool {
	return true
}

func (s *RemoveDatabaseStatement) Writeable() bool {
	return true
}

func (s *DefineLoginStatement) Writeable() bool {
	return true
}

func (s *RemoveLoginStatement) Writeable() bool {
	return true
}

func (s *DefineTokenStatement) Writeable() bool {
	return true
}

func (s *RemoveTokenStatement) Writeable() bool {
	return true
}

func (s *DefineScopeStatement) Writeable() bool {
	return true
}

func (s *RemoveScopeStatement) Writeable() bool {
	return true
}

func (s *DefineTableStatement) Writeable() bool {
	return true
}

func (s *RemoveTableStatement) Writeable() bool {
	return true
}

func (s *DefineEventStatement) Writeable() bool {
	return true
}

func (s *RemoveEventStatement) Writeable() bool {
	return true
}

func (s *DefineFieldStatement) Writeable() bool {
	return true
}

func (s *RemoveFieldStatement) Writeable() bool {
	return true
}

func (s *DefineIndexStatement) Writeable() bool {
	return true
}

func (s *RemoveIndexStatement) Writeable() bool {
	return true
}
