[package]
name = "surrealdb-rpc"
publish = true
edition.workspace = true
version.workspace = true
authors.workspace = true
license-file.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
surrealdb-types = { workspace = true }
anyhow = { workspace = true }
humantime = { workspace = true }
revision = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde", "v4", "v7"] }
web-time = { workspace = true }

[lints]
workspace = true
