on:
  workflow_call:
    inputs:
      git-ref:
        required: false
        type: string
        description: "The git ref of this release version. All 'actions/checkout' steps will use it"
      nightly-release:
        required: false
        type: boolean
        default: true
        description: "Make this a nightly release"
      publish:
        required: false
        type: boolean
        default: false
        description: "Whether to publish this release"
      rust-version:
        required: false
        type: string
        default: "1.90"
        description: "The Rust version to use for building binaries"
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true
        description: "Token for publishing to crates.io"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  publish-crate:
    name: Publish crate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ inputs.git-ref }}

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # stable (Actions must be pinned by commit hash)
        with:
          toolchain: ${{ inputs.rust-version }}

      - name: Install release-plz
        run: |
          curl -L https://github.com/MarcoIeni/release-plz/releases/download/release-plz-v0.3.30/release-plz-x86_64-unknown-linux-gnu.tar.gz | sudo tar -xz -C /usr/bin
          sudo chmod +x /usr/bin/release-plz

      - name: Configure release-plz
        run: |
          cat << EOF > /tmp/release-plz.toml
          [workspace]
          changelog_update = false
          git_release_enable = false
          semver_check = false
          git_tag_enable = false
          EOF

      - name: Publish the crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          set -x

          # Create a temporary branch in case the git ref is not a branch
          git checkout -b crate

          extra_args=""

          if [[ "${{ inputs.publish }}" == "false" || "${{ inputs.nightly-release }}" == "true" ]]; then
            # Dry run to test publishing
            extra_args="${extra_args} --dry-run"
          fi

          release-plz release --config /tmp/release-plz.toml ${extra_args}
