name: "Labeler"
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  triage:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: github/issue-labeler@6bea9ed491bb74fce38775b3d863e64a59dbd9eb # (Actions must be pinned by commit hash) v3.3
        with:
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0
          include-title: 1
          include-body: 1
          sync-labels: 0
