name: Nix

on:
  push:
    branches:
      - main
  pull_request:
    types: [ labeled ]

# Setting the shell option, it will run 'bash --noprofile --norc -eo pipefail {0}'
defaults:
  run:
    shell: bash

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  # TODO: Figure out why it fails to build
  # 
  # build-static:
  #   name: Build static Linux binary
  #   if: ${{ github.ref == 'refs/heads/main' }} || ${{ github.event.label.name == 'nix' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  #     - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
  #     - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # v14
  #       with:
  #         name: surrealdb
  #         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
  #         extraPullNames: nix-community
  #     - run: nix build .#static-binary
  #     - run: ./result/bin/surreal help

  build-docker:
    name: Build Docker image
    if: ${{ github.ref == 'refs/heads/main' }} || ${{ github.event.label.name == 'nix' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # (Actions must be pinned by commit hash) v4.2.2
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # (Actions must be pinned by commit hash) v26
      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # (Actions must be pinned by commit hash) v14
        with:
          name: surrealdb
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - run: nix build .#docker-image
      - run: docker load --input ./result

  build-native-linux:
    name: Build native Linux binary
    if: ${{ github.ref == 'refs/heads/main' }} || ${{ github.event.label.name == 'nix' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # (Actions must be pinned by commit hash) v4.2.2
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # (Actions must be pinned by commit hash) v26
      - uses: cachix/cachix-action@18cf96c7c98e048e10a83abd92116114cd8504be # (Actions must be pinned by commit hash) v14
        with:
          name: surrealdb
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community
      - run: nix build .#x86_64-unknown-linux-gnu
      - run: ./result/bin/surreal help
