/**
[test]

[[test.results]]
value = "NONE"

[[test.results]]
value = "NONE"

[[test.results]]
value = "NONE"

[[test.results]]
value = "NONE"

[[test.results]]
value = "NONE"

[[test.results]]
value = "NONE"

[[test.results]]
value = "NONE"
*/

DEFINE FIELD flexible ON tab FLEXIBLE;
DEFINE FIELD readonly ON tab READONLY;
DEFINE FIELD comment ON tab COMMENT "a comment";
DEFINE FIELD type ON tab TYPE any;
DEFINE FIELD value ON tab VALUE 1;
DEFINE FIELD assert ON tab ASSERT true;
DEFINE FIELD default ON tab DEFAULT 1;
