apiVersion: 1
deleteDatasources:
  - name: Prometheus
  - name: Tempo
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    withCredentials: false
    isDefault: true
    tlsAuth: false
    tlsAuthWithCACert: false
    version: 1
    editable: true
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
