global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9500"]
  
  - job_name: 'tempo'
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: otel-collector
    static_configs:
      # Scrap the SurrealDB metrics sent to OpenTelemetry collector
      - targets: ["otel-collector:9090"]
