/**
[test]

[[test.results]]
value = "true"

[[test.results]]
value = "true"

[[test.results]]
value = "false"

[[test.results]]
value = "true"

[[test.results]]
value = "true"

[[test.results]]
value = "false"

[[test.results]]
value = "true"

[[test.results]]
value = "true"

[[test.results]]
value = "false"

*/
RETURN NONE = NONE;
RETURN NULL = NULL;
RETURN NONE = NULL;
RETURN [] = [];
RETURN {} = {};
RETURN [] = {};
RETURN 0 = 0;
RETURN 0 = 0.0;
RETURN 0 = 0.1;
